### ISSUE TITLE
RainDrop测试集psnr

### ISSUE THREAD

**Issue by Sportlich** [sunshangquan/Histoformer#10]
你好，我下载了RainDrop 链接中的test_b 的测试集（249对图片）  并使用net_g_best.pth进行修复 算得的psnr是26.866  这与文章中的psnr不匹配 我不知道是不是测试集不对还是其他什么原因 。
其他三个没有类似的问题。
期待你的回复。

**Comment by sunshangquan** [comment]
Hi @Sportlich , there are two sub-testsets in RainDrop, i.e., test_a (58 pairs) and test_b (249 pairs). Its authors recommend to compare quantitative results like psnr and ssim on test_a because some pairs in test_b is not pixel-wisely aligned or matched. Please try computing psnr on test_a [accordingly](https://github.com/rui1996/DeRaindrop).
