### ISSUE TITLE
Error when using direct tests

### ISSUE THREAD

**Issue by icewindi** [sunshangquan/Histoformer#6]
Thank you for your wonderful work. However, I am having problems with the direct testing process. When using the Demo direct test, it did not run successfully. The following error appears:

  File "test_histoformer.py", line 15, in <module>
    from basicsr.models.archs.histoformer_arch import Histoformer
  File "D:\code\Histoformer-main\basicsr\models\__init__.py", line 16, in <module>
    _model_modules = [
  File "D:\code\Histoformer-main\basicsr\models\__init__.py", line 17, in <listcomp>
    importlib.import_module(f'models.{file_name}')
  File "C:\Users\anaconda3\envs\dez\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'models'

Would you be able to advise where the code is having problems, thanks.

**Comment by sunshangquan** [comment]
Hi @icewindi , I guess the problem comes the logic difference of appending path between my Linux server and your machine. You could try (a) modifying the path at [test_histoformer.py L14](https://github.com/sunshangquan/Histoformer/blob/main/Allweather/test_histoformer.py#L14) into your path, and if it does not work, then try (b) adding "basicsr" to "D:\code\Histoformer-main\basicsr\models_init.py", line 17, which will be ```importlib.import_module(f'basicsr.models.{file_name}')``` . 

My local Linux machine and remote server also have such kind of difference in terms of whether "basicsr" is needed during running training and testing. It has two potential reasons, i.e., a) whether you are calling the "basicsr" that is pip-installed or the one at ```Histoformer``` path; b) whether your root or appended path is at ```Histoformer``` or ```Histoformer/basicsr```. The similar issues are also found in [Restormer](https://github.com/swz30/Restormer/issues/97).

I will check this issue in a few days and update it into a more versatile way by testing on several more machines.

**Comment by icewindi** [comment]
Thank you for your reply. I tried adding “basicsr” to solve the problem and successfully tested it. However, running the code correctly in my environment still requires adjusting the location of multiple libraries to run correctly.

**Comment by sunshangquan** [comment]
Glad that you solved it! I also met the issue before on a different machine and need to adjust libraries in multiple files. I will tune them in a few days into a more versatile way.

**Comment by ll000x** [comment]
您好 我是初学者，首先您的代码是要在linux系统跑吗，其次若您方便的话可以出比较详细的运行操作吗 谢谢您

**Comment by sunshangquan** [comment]
Hi @ll000x , yes the code was run on Linux. Sorry but I was preparing other works in the last weeks. I will fix this problem in a few days. You could try yourself and if you meet any specific problem, please feel free to open another issue.

**Comment by sunshangquan** [comment]
Hi @icewindi @ll000x , I have fixed the ```import``` issues on another local machine. Please feel free to raise them if there are remaining issues.
